"""initial schema

Revision ID: 2679d5a12c9a
Revises:
Create Date: 2026-09-10 00:31:00.891097

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2679d5a12c9a"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "approval_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("memo_content_hash", sa.String(length=64), nullable=False),
        sa.Column("export_type", sa.String(length=32), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approval_requests")),
    )
    with op.batch_alter_table("approval_requests", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_approval_requests_run_id"), ["run_id"], unique=False)

    op.create_table(
        "companies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ticker", sa.String(length=16), nullable=False),
        sa.Column("cik", sa.String(length=10), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("sector", sa.String(length=64), nullable=True),
        sa.Column("industry", sa.String(length=128), nullable=True),
        sa.Column("country", sa.String(length=8), nullable=True),
        sa.Column("reporting_currency", sa.String(length=8), nullable=True),
        sa.Column("fiscal_year_end", sa.String(length=5), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_companies")),
    )
    with op.batch_alter_table("companies", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_companies_cik"), ["cik"], unique=True)
        batch_op.create_index(batch_op.f("ix_companies_ticker"), ["ticker"], unique=True)

    op.create_table(
        "eval_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dataset_version", sa.String(length=64), nullable=True),
        sa.Column("chunking_strategy", sa.String(length=32), nullable=True),
        sa.Column("retrieval_config", sa.String(length=64), nullable=True),
        sa.Column("config_json", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_eval_runs")),
    )
    op.create_table(
        "run_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("event_json", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_run_events")),
    )
    with op.batch_alter_table("run_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_run_events_run_id"), ["run_id"], unique=False)

    op.create_table(
        "runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("endpoint", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("params_json", sa.Text(), nullable=True),
        sa.Column("error_type", sa.String(length=128), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_runs")),
    )
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_runs_run_id"), ["run_id"], unique=True)

    op.create_table(
        "source_artifacts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("local_path", sa.Text(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("content_type", sa.String(length=128), nullable=True),
        sa.Column("http_etag", sa.String(length=255), nullable=True),
        sa.Column("http_last_modified", sa.String(length=255), nullable=True),
        sa.Column("parser_version", sa.String(length=32), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_artifacts")),
    )
    op.create_table(
        "agent_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=True),
        sa.Column("intent", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=True),
        sa.Column("tool_call_count", sa.Integer(), nullable=False),
        sa.Column("transition_count", sa.Integer(), nullable=False),
        sa.Column("state_json", sa.Text(), nullable=True),
        sa.Column("error_type", sa.String(length=128), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_agent_runs_company_id_companies")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_runs")),
    )
    with op.batch_alter_table("agent_runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_agent_runs_run_id"), ["run_id"], unique=True)

    op.create_table(
        "brief_cache",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cache_key", sa.String(length=64), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=True),
        sa.Column("period_end", sa.Date(), nullable=True),
        sa.Column("provider", sa.String(length=32), nullable=True),
        sa.Column("model", sa.String(length=128), nullable=True),
        sa.Column("prompt_version", sa.String(length=32), nullable=True),
        sa.Column("response_json", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_brief_cache_company_id_companies")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_brief_cache")),
    )
    with op.batch_alter_table("brief_cache", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_brief_cache_cache_key"), ["cache_key"], unique=True)

    op.create_table(
        "derived_metrics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=True),
        sa.Column("metric", sa.String(length=64), nullable=False),
        sa.Column("value_decimal", sa.Text(), nullable=True),
        sa.Column("unit", sa.String(length=32), nullable=True),
        sa.Column("formula_version", sa.String(length=32), nullable=True),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("input_fact_ids_json", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_derived_metrics_company_id_companies")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_derived_metrics")),
    )
    with op.batch_alter_table("derived_metrics", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_derived_metrics_company_id"), ["company_id"], unique=False
        )

    op.create_table(
        "documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("accession", sa.String(length=32), nullable=True),
        sa.Column("form", sa.String(length=16), nullable=True),
        sa.Column("document_kind", sa.String(length=32), nullable=True),
        sa.Column("period_end", sa.Date(), nullable=True),
        sa.Column("filed_at", sa.Date(), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("source_artifact_id", sa.Integer(), nullable=True),
        sa.Column("extracted_path", sa.Text(), nullable=True),
        sa.Column("extraction_version", sa.String(length=32), nullable=True),
        sa.Column("extraction_status", sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_documents_company_id_companies")
        ),
        sa.ForeignKeyConstraint(
            ["source_artifact_id"],
            ["source_artifacts.id"],
            name=op.f("fk_documents_source_artifact_id_source_artifacts"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
    )
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_documents_company_id"), ["company_id"], unique=False)

    op.create_table(
        "eval_results",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("eval_run_id", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.String(length=128), nullable=False),
        sa.Column("metric_name", sa.String(length=64), nullable=False),
        sa.Column("value", sa.Text(), nullable=True),
        sa.Column("details_json", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["eval_run_id"], ["eval_runs.id"], name=op.f("fk_eval_results_eval_run_id_eval_runs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_eval_results")),
    )
    with op.batch_alter_table("eval_results", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_eval_results_eval_run_id"), ["eval_run_id"], unique=False
        )

    op.create_table(
        "fact_observations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("source_artifact_id", sa.Integer(), nullable=True),
        sa.Column("accession", sa.String(length=32), nullable=True),
        sa.Column("form", sa.String(length=16), nullable=True),
        sa.Column("filed_at", sa.Date(), nullable=True),
        sa.Column("taxonomy", sa.String(length=64), nullable=False),
        sa.Column("original_tag", sa.String(length=128), nullable=False),
        sa.Column("canonical_concept", sa.String(length=64), nullable=False),
        sa.Column("value_decimal", sa.Text(), nullable=True),
        sa.Column("unit", sa.String(length=32), nullable=True),
        sa.Column("currency", sa.String(length=8), nullable=True),
        sa.Column("period_start", sa.Date(), nullable=True),
        sa.Column("period_end", sa.Date(), nullable=True),
        sa.Column("period_kind", sa.String(length=20), nullable=False),
        sa.Column("source_fy", sa.Integer(), nullable=True),
        sa.Column("source_fp", sa.String(length=8), nullable=True),
        sa.Column("reporting_scope", sa.String(length=32), nullable=True),
        sa.Column("context_metadata_json", sa.Text(), nullable=True),
        sa.Column("observation_hash", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_fact_observations_company_id_companies")
        ),
        sa.ForeignKeyConstraint(
            ["source_artifact_id"],
            ["source_artifacts.id"],
            name=op.f("fk_fact_observations_source_artifact_id_source_artifacts"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fact_observations")),
        sa.UniqueConstraint("observation_hash", name=op.f("uq_fact_observations_observation_hash")),
    )
    with op.batch_alter_table("fact_observations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_fact_observations_company_id"), ["company_id"], unique=False
        )

    op.create_table(
        "normalized_facts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("concept", sa.String(length=64), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=True),
        sa.Column("period_end", sa.Date(), nullable=True),
        sa.Column("fiscal_year", sa.Integer(), nullable=True),
        sa.Column("fiscal_quarter", sa.String(length=8), nullable=True),
        sa.Column("period_kind", sa.String(length=20), nullable=False),
        sa.Column("reporting_scope", sa.String(length=32), nullable=False),
        sa.Column("value_decimal", sa.Text(), nullable=True),
        sa.Column("unit", sa.String(length=32), nullable=True),
        sa.Column("selection_policy", sa.String(length=32), nullable=True),
        sa.Column("normalization_version", sa.String(length=32), nullable=True),
        sa.Column("is_derived", sa.Boolean(), nullable=False),
        sa.Column("derivation_method", sa.String(length=128), nullable=True),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("data_quality_status", sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_normalized_facts_company_id_companies")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_normalized_facts")),
        sa.UniqueConstraint(
            "company_id",
            "concept",
            "period_start",
            "period_end",
            "period_kind",
            "reporting_scope",
            name="uq_normalized_facts_period_identity",
        ),
    )
    with op.batch_alter_table("normalized_facts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_normalized_facts_company_id"), ["company_id"], unique=False
        )

    op.create_table(
        "prices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=True),
        sa.Column("open", sa.Text(), nullable=True),
        sa.Column("high", sa.Text(), nullable=True),
        sa.Column("low", sa.Text(), nullable=True),
        sa.Column("close", sa.Text(), nullable=True),
        sa.Column("volume", sa.BigInteger(), nullable=True),
        sa.Column("currency", sa.String(length=8), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=True),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_prices_company_id_companies")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prices")),
        sa.UniqueConstraint("company_id", "trade_date", name="uq_prices_company_trade_date"),
    )
    with op.batch_alter_table("prices", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_prices_company_id"), ["company_id"], unique=False)

    op.create_table(
        "agent_tool_calls",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("agent_run_id", sa.Integer(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("tool_name", sa.String(length=64), nullable=False),
        sa.Column("arguments_json", sa.Text(), nullable=True),
        sa.Column("result_json", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["agent_run_id"],
            ["agent_runs.id"],
            name=op.f("fk_agent_tool_calls_agent_run_id_agent_runs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_tool_calls")),
    )
    with op.batch_alter_table("agent_tool_calls", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_agent_tool_calls_agent_run_id"), ["agent_run_id"], unique=False
        )

    op.create_table(
        "fact_lineage",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("normalized_fact_id", sa.Integer(), nullable=False),
        sa.Column("source_observation_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["normalized_fact_id"],
            ["normalized_facts.id"],
            name=op.f("fk_fact_lineage_normalized_fact_id_normalized_facts"),
        ),
        sa.ForeignKeyConstraint(
            ["source_observation_id"],
            ["fact_observations.id"],
            name=op.f("fk_fact_lineage_source_observation_id_fact_observations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fact_lineage")),
    )
    with op.batch_alter_table("fact_lineage", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_fact_lineage_normalized_fact_id"), ["normalized_fact_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_fact_lineage_source_observation_id"),
            ["source_observation_id"],
            unique=False,
        )

    op.create_table(
        "sections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("section_type", sa.String(length=32), nullable=True),
        sa.Column("heading", sa.Text(), nullable=True),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("start_offset", sa.Integer(), nullable=True),
        sa.Column("end_offset", sa.Integer(), nullable=True),
        sa.Column("page_start", sa.Integer(), nullable=True),
        sa.Column("page_end", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["document_id"], ["documents.id"], name=op.f("fk_sections_document_id_documents")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sections")),
    )
    with op.batch_alter_table("sections", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sections_document_id"), ["document_id"], unique=False)

    op.create_table(
        "chunks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("section_id", sa.Integer(), nullable=True),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("strategy", sa.String(length=32), nullable=False),
        sa.Column("strategy_version", sa.String(length=32), nullable=False),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("text_hash", sa.String(length=64), nullable=True),
        sa.Column("token_count", sa.Integer(), nullable=True),
        sa.Column("start_offset", sa.Integer(), nullable=True),
        sa.Column("end_offset", sa.Integer(), nullable=True),
        sa.Column("page_start", sa.Integer(), nullable=True),
        sa.Column("page_end", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["document_id"], ["documents.id"], name=op.f("fk_chunks_document_id_documents")
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["chunks.id"], name=op.f("fk_chunks_parent_id_chunks")
        ),
        sa.ForeignKeyConstraint(
            ["section_id"], ["sections.id"], name=op.f("fk_chunks_section_id_sections")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chunks")),
        sa.UniqueConstraint(
            "document_id", "strategy", "strategy_version", "text_hash", name="uq_chunks_identity"
        ),
    )
    with op.batch_alter_table("chunks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_chunks_document_id"), ["document_id"], unique=False)

    op.create_table(
        "embeddings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chunk_id", sa.Integer(), nullable=False),
        sa.Column("text_hash", sa.String(length=64), nullable=True),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("model_revision", sa.String(length=128), nullable=True),
        sa.Column("dimension", sa.Integer(), nullable=True),
        sa.Column("normalized", sa.Boolean(), nullable=True),
        sa.Column("vector", sa.LargeBinary(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["chunk_id"], ["chunks.id"], name=op.f("fk_embeddings_chunk_id_chunks")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_embeddings")),
        sa.UniqueConstraint(
            "chunk_id", "provider", "model", "model_revision", name="uq_embeddings_identity"
        ),
    )
    with op.batch_alter_table("embeddings", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_embeddings_chunk_id"), ["chunk_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("embeddings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_embeddings_chunk_id"))

    op.drop_table("embeddings")
    with op.batch_alter_table("chunks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_chunks_document_id"))

    op.drop_table("chunks")
    with op.batch_alter_table("sections", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sections_document_id"))

    op.drop_table("sections")
    with op.batch_alter_table("fact_lineage", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_fact_lineage_source_observation_id"))
        batch_op.drop_index(batch_op.f("ix_fact_lineage_normalized_fact_id"))

    op.drop_table("fact_lineage")
    with op.batch_alter_table("agent_tool_calls", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_agent_tool_calls_agent_run_id"))

    op.drop_table("agent_tool_calls")
    with op.batch_alter_table("prices", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_prices_company_id"))

    op.drop_table("prices")
    with op.batch_alter_table("normalized_facts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_normalized_facts_company_id"))

    op.drop_table("normalized_facts")
    with op.batch_alter_table("fact_observations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_fact_observations_company_id"))

    op.drop_table("fact_observations")
    with op.batch_alter_table("eval_results", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_eval_results_eval_run_id"))

    op.drop_table("eval_results")
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_documents_company_id"))

    op.drop_table("documents")
    with op.batch_alter_table("derived_metrics", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_derived_metrics_company_id"))

    op.drop_table("derived_metrics")
    with op.batch_alter_table("brief_cache", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_brief_cache_cache_key"))

    op.drop_table("brief_cache")
    with op.batch_alter_table("agent_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_agent_runs_run_id"))

    op.drop_table("agent_runs")
    op.drop_table("source_artifacts")
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_runs_run_id"))

    op.drop_table("runs")
    with op.batch_alter_table("run_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_run_events_run_id"))

    op.drop_table("run_events")
    op.drop_table("eval_runs")
    with op.batch_alter_table("companies", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_companies_ticker"))
        batch_op.drop_index(batch_op.f("ix_companies_cik"))

    op.drop_table("companies")
    with op.batch_alter_table("approval_requests", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_approval_requests_run_id"))

    op.drop_table("approval_requests")
    # ### end Alembic commands ###
