"""document extraction metadata

Revision ID: 52e66ea29e8e
Revises: 2679d5a12c9a
Create Date: 2026-09-10 02:04:14.212870

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "52e66ea29e8e"
down_revision: str | Sequence[str] | None = "2679d5a12c9a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.add_column(sa.Column("event_date", sa.Date(), nullable=True))
        batch_op.add_column(sa.Column("extraction_notes", sa.Text(), nullable=True))

    with op.batch_alter_table("sections", schema=None) as batch_op:
        batch_op.add_column(sa.Column("confidence", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("notes", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sections", schema=None) as batch_op:
        batch_op.drop_column("notes")
        batch_op.drop_column("confidence")

    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.drop_column("extraction_notes")
        batch_op.drop_column("event_date")

    # ### end Alembic commands ###
