"""Financial ratio calculations (SPEC 11). All money math is ``Decimal``.

Every calculator returns a ``MetricValue`` carrying the value, unit, status,
input references and ``formula_version`` (SPEC 11: "Return a value, units,
input references, and status").

Sign conventions (documented tag semantics, ``capex-semantics-v1``):
- ``cfo``: as reported; positive = cash generated by operations.
- ``capex_outflow``: US-GAAP ``PaymentsToAcquirePropertyPlantAndEquipment`` is
  reported as a NEGATIVE number (cash outflow) in the cash-flow statement. The
  observation keeps the reported sign; the normalized metric presents the
  outflow as a positive magnitude so ``fcf = cfo - capex_outflow`` matches
  SPEC 11.1 literally. A capex value reported with an unexpected sign is
  flagged for review in ``notes`` - never hidden with ``abs()``.

Growth (SPEC 11.2): ``growth = current / prior - 1`` only for positive priors;
a zero or negative prior yields a null percentage growth plus the absolute
change and an optional deterministic turned-profitable/loss-making note. Margin
changes are expressed in PERCENTAGE POINTS. Cash conversion is only valid when
net income is positive; otherwise the ratio is marked ``unsuitable`` (SPEC 11.3).
"""

from __future__ import annotations

from decimal import Decimal

from quarterline.core.models import MetricProvenance, MetricStatus, MetricValue

#: Bumped when any formula or threshold below changes; persisted on metrics.
FORMULA_VERSION_RATIOS = "ratios-v1"
#: Documented tag-sign semantics for the capex normalization.
FORMULA_VERSION_CAPEX_SEMANTICS = "capex-semantics-v1"

UNIT_USD = "USD"
UNIT_RATIO = "ratio"
UNIT_PERCENTAGE_POINTS = "percentage_points"
UNIT_SHARES = "shares"
UNIT_USD_PER_SHARE = "USD/shares"

ZERO = Decimal(0)
ONE_HUNDRED = Decimal(100)


def _value(
    metric_id: str,
    value: Decimal | None,
    unit: str | None,
    status: MetricStatus,
    input_refs: list[str] | None = None,
    formula_version: str | None = FORMULA_VERSION_RATIOS,
    notes: list[str] | None = None,
) -> MetricValue:
    return MetricValue(
        metric_id=metric_id,
        value=value,
        unit=unit,
        status=status,
        provenance=MetricProvenance(
            observation_ids=[],
            derived_from=input_refs or [],
            formula_version=formula_version,
        ),
        notes=notes or [],
    )


def _divide(numerator: Decimal, denominator: Decimal) -> Decimal | None:
    """Exact division; ``None`` when the denominator is zero.

    Negative denominators are mathematically defined but reported for review by
    the callers that consider them invalid (SPEC 26: zero and negative
    denominator handling).
    """
    if denominator == ZERO:
        return None
    return numerator / denominator


def _simple_ratio_metric(
    metric_id: str,
    numerator: Decimal | None,
    denominator: Decimal | None,
    *,
    numerator_ref: str,
    denominator_ref: str,
    notes: list[str] | None = None,
) -> MetricValue:
    refs = [numerator_ref, denominator_ref]
    missing = [
        ref
        for ref, value in ((numerator_ref, numerator), (denominator_ref, denominator))
        if value is None
    ]
    if missing:
        return _value(
            metric_id,
            None,
            UNIT_RATIO,
            MetricStatus.missing,
            input_refs=refs,
            notes=[f"missing input(s): {', '.join(missing)}"] + (notes or []),
        )
    assert numerator is not None and denominator is not None  # narrowing
    if denominator == ZERO:
        return _value(
            metric_id,
            None,
            UNIT_RATIO,
            MetricStatus.invalid,
            input_refs=refs,
            notes=["zero denominator; ratio undefined"] + (notes or []),
        )
    if denominator < ZERO:
        return _value(
            metric_id,
            None,
            UNIT_RATIO,
            MetricStatus.invalid,
            input_refs=refs,
            notes=["negative denominator; ratio not meaningful"] + (notes or []),
        )
    quotient = _divide(numerator, denominator)
    return _value(metric_id, quotient, UNIT_RATIO, MetricStatus.ok, input_refs=refs, notes=notes)


#: (numerator concept, denominator concept) per margin-style metric.
_RATIO_INPUT_REFS = {
    "gross_margin": ("gross_profit", "revenue"),
    "operating_margin": ("operating_income", "revenue"),
    "net_margin": ("net_income", "revenue"),
    "fcf_margin": ("fcf", "revenue"),
    "current_ratio": ("current_assets", "current_liabilities"),
}


def margin(metric_id: str, profit: Decimal | None, revenue: Decimal | None) -> MetricValue:
    """gross/operating/net margin = profit / revenue (SPEC 11.1)."""
    numerator_ref, denominator_ref = _RATIO_INPUT_REFS[metric_id]
    return _simple_ratio_metric(
        metric_id,
        profit,
        revenue,
        numerator_ref=numerator_ref,
        denominator_ref=denominator_ref,
    )


def current_ratio(
    current_assets: Decimal | None, current_liabilities: Decimal | None
) -> MetricValue:
    return _simple_ratio_metric(
        "current_ratio",
        current_assets,
        current_liabilities,
        numerator_ref="current_assets",
        denominator_ref="current_liabilities",
    )


def capex_outflow_metric(reported_capex: Decimal | None) -> MetricValue:
    """Normalize reported capex to a positive outflow magnitude (SPEC 11.1).

    The reported sign is preserved in the observation; a positive reported
    value (inflow semantics) is unexpected and is flagged for review instead of
    being silently absorbed by ``abs()``.
    """
    if reported_capex is None:
        return _value(
            "capex_outflow",
            None,
            UNIT_USD,
            MetricStatus.missing,
            notes=["missing input(s): capex_outflow"],
        )
    if reported_capex > ZERO:
        return _value(
            "capex_outflow",
            reported_capex,
            UNIT_USD,
            MetricStatus.ok,
            input_refs=["capex_outflow:reported_positive"],
            formula_version=FORMULA_VERSION_CAPEX_SEMANTICS,
            notes=[
                (
                    "unexpected sign: capex reported as a POSITIVE value; treating as outflow "
                    "magnitude - flag for review (not hidden with abs())"
                )
            ],
        )
    if reported_capex == ZERO:
        return _value(
            "capex_outflow",
            ZERO,
            UNIT_USD,
            MetricStatus.ok,
            input_refs=["capex_outflow:reported_zero"],
            formula_version=FORMULA_VERSION_CAPEX_SEMANTICS,
            notes=["capex reported as zero"],
        )
    return _value(
        "capex_outflow",
        -reported_capex,
        UNIT_USD,
        MetricStatus.ok,
        input_refs=["capex_outflow:reported_negative_negated"],
        formula_version=FORMULA_VERSION_CAPEX_SEMANTICS,
        notes=["capex reported negative (cash outflow); presented as positive outflow magnitude"],
    )


def free_cash_flow(cfo: Decimal | None, reported_capex: Decimal | None) -> MetricValue:
    """``fcf = cfo - capex_outflow`` with documented capex sign semantics."""
    capex = capex_outflow_metric(reported_capex)
    if cfo is None or capex.value is None:
        missing = [
            name for name, value in (("cfo", cfo), ("capex_outflow", capex.value)) if value is None
        ]
        return _value(
            "fcf",
            None,
            UNIT_USD,
            MetricStatus.missing,
            input_refs=["cfo", "capex_outflow"],
            notes=[f"missing input(s): {', '.join(missing)}"] + capex.notes,
        )
    notes = list(capex.notes)
    return _value(
        "fcf",
        cfo - capex.value,
        UNIT_USD,
        MetricStatus.ok,
        input_refs=["cfo", "capex_outflow"],
        notes=notes,
    )


def fcf_margin(fcf: Decimal | None, revenue: Decimal | None) -> MetricValue:
    return _simple_ratio_metric("fcf_margin", fcf, revenue, input_refs=["fcf", "revenue"])


def long_term_net_debt_proxy(long_term_debt: Decimal | None, cash: Decimal | None) -> MetricValue:
    """``long_term_debt - cash``. A PROXY, never presented as total net debt."""
    if long_term_debt is None or cash is None:
        missing = [n for n, v in (("long_term_debt", long_term_debt), ("cash", cash)) if v is None]
        return _value(
            "long_term_net_debt_proxy",
            None,
            UNIT_USD,
            MetricStatus.missing,
            input_refs=["long_term_debt", "cash"],
            notes=[f"missing input(s): {', '.join(missing)}"],
        )
    return _value(
        "long_term_net_debt_proxy",
        long_term_debt - cash,
        UNIT_USD,
        MetricStatus.ok,
        input_refs=["long_term_debt", "cash"],
        notes=[
            (
                "proxy only: long-term debt minus cash and cash equivalents; excludes short-term "
                "debt, leases and investments - not total net debt"
            )
        ],
    )


def yoy_growth(
    metric_id: str,
    current: Decimal | None,
    prior: Decimal | None,
    unit: str | None,
) -> MetricValue:
    """Year-over-year growth for matching fiscal quarters (SPEC 11.2).

    The caller must supply a prior value for the MATCHING fiscal quarter, never
    an arbitrary four-row offset. A zero or negative prior yields a null
    percentage growth, the absolute change, and a deterministic
    turned-profitable / turned-loss-making note when applicable.
    """
    refs = [f"{metric_id}:current", f"{metric_id}:prior_year_quarter"]
    if current is None or prior is None:
        return _value(
            metric_id,
            None,
            unit,
            MetricStatus.missing,
            input_refs=refs,
            notes=["missing input(s): current or matching prior-year quarter"],
        )
    if prior < ZERO:
        note = None
        if current > ZERO:
            note = "turned profitable: prior-year quarter was a loss"
        elif current < ZERO:
            note = "prior-year quarter was a loss and remains a loss"
        return _value(
            metric_id,
            None,
            unit,
            MetricStatus.unsuitable,
            input_refs=refs,
            notes=["negative prior value; percentage growth not meaningful"]
            + ([note] if note else [])
            + [f"absolute change: {current - prior}"],
        )
    if prior == ZERO:
        note = "turned profitable: prior-year quarter was zero" if current > ZERO else None
        notes = ["zero prior value; percentage growth undefined"] + ([note] if note else [])
        notes.append(f"absolute change: {current}")
        return _value(metric_id, None, unit, MetricStatus.unsuitable, input_refs=refs, notes=notes)
    growth = current / prior - Decimal(1)
    notes: list[str] = []
    if current < ZERO:
        notes.append("current value is negative while prior is positive (turned loss-making)")
    notes.append(f"absolute change: {current - prior}")
    return _value(metric_id, growth, unit, MetricStatus.ok, input_refs=refs, notes=notes)


def margin_change_pp(
    metric_id: str, current_margin: Decimal | None, prior_margin: Decimal | None
) -> MetricValue:
    """Margin change in PERCENTAGE POINTS (SPEC 11.2), not a relative ratio."""
    refs = [f"{metric_id}:current", f"{metric_id}:prior_year_quarter"]
    if current_margin is None or prior_margin is None:
        return _value(
            metric_id,
            None,
            UNIT_PERCENTAGE_POINTS,
            MetricStatus.missing,
            input_refs=refs,
            notes=["missing input(s): current or prior-year margin"],
        )
    change = (current_margin - prior_margin) * ONE_HUNDRED
    return _value(
        metric_id,
        change,
        UNIT_PERCENTAGE_POINTS,
        MetricStatus.ok,
        input_refs=refs,
    )


def cfo_to_net_income(cfo: Decimal | None, net_income: Decimal | None) -> MetricValue:
    """Cash conversion (SPEC 11.3): only valid when net income is positive.

    A zero or negative net income marks the ratio ``unsuitable`` for scoring;
    CFO and net income remain visible as inputs.
    """
    refs = ["cfo", "net_income"]
    if cfo is None or net_income is None:
        missing = [n for n, v in (("cfo", cfo), ("net_income", net_income)) if v is None]
        return _value(
            "cfo_to_net_income",
            None,
            UNIT_RATIO,
            MetricStatus.missing,
            input_refs=refs,
            notes=[f"missing input(s): {', '.join(missing)}"],
        )
    if net_income <= ZERO:
        return _value(
            "cfo_to_net_income",
            None,
            UNIT_RATIO,
            MetricStatus.unsuitable,
            input_refs=refs,
            notes=[
                (
                    f"net income is {net_income} (zero or negative); ratio unsuitable for scoring - "
                    f"cfo={cfo}, net_income={net_income} shown separately"
                )
            ],
        )
    return _value(
        "cfo_to_net_income", _divide(cfo, net_income), UNIT_RATIO, MetricStatus.ok, input_refs=refs
    )
